name: bleyldev_website
description: Bleyl Dev landing page

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  google_fonts: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf


  assets:
    - assets/cover.png
    - assets/logo_appbar.png
    - assets/youtube_panel.png
    - assets/profile.jpg
    - assets/flutter_logo.png

