name: bleyldev_website
description: Bleyl Dev Website

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  google_fonts: ^1.1.0
  firebase_core: "^0.5.0+1"
  cloud_firestore: "^0.14.1+3"

  http: ^0.12.2
  flutter_widget_from_html_core: ^0.5.1+1
  youtube_player_iframe: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf


  assets:
    - assets/cover.png
    - assets/home_banner.png
    - assets/home_banner_tall.png
    - assets/logo_appbar.png
    - assets/youtube_panel.png
    - assets/profile.jpg
    - assets/flutter_logo.png
    - assets/flutter_developer_infographic.png

